version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Installing HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
      - ./packer validate copy-packer-code.json

  build:
    commands:
      ./packer build copy-packer-code.json
  post_build:
    commands:
      -echo "Packer build complted on 'date'"
