version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - /packer validate copy-sample-packer.json

  build:
    commands:
      ./packer build sample-packer-code.json
  post_build:
    commands:
      -echo "Packer build complted on 'date'"
